server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload-path: d:/common_boil/uploads
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.common.entity
jwt:
  secret: handsomeGuy
  expiration: 86400