server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://test-server:3306/common_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test
    password: test123
  mail:
    host: smtp.qq.com
    username: test-email@qq.com
    password: test-password
    port: 587

file:
  upload-path: d:/common_boil/uploads/test